/* CCDAK length-balance + flip. After de-bias the correct option was still the
 * longest in ~93% of questions. Trim over-long correct options (detail is in the
 * notes) and extend the top distractor just past the correct answer with a
 * plausible, still-wrong clause, so length no longer predicts the answer.
 * Covers kk-001..090 and the pre-existing detailed set kk-091..115. */
module.exports = {
  questions: {
    // --- detailed set (kk-091..115): trim long correct + extend top distractor ---
    "kk-091": { optionEdits: { 0: "Writes succeeded with one broker down, but with two down they fail (NotEnoughReplicas)", 1: "Writes continue normally as long as any single broker stays alive, since the leader can always acknowledge on its own" } },
    "kk-092": { optionEdits: { 0: "One consumer stays idle — partitions aren't shared, so at most 3 consumers get an assignment", 2: "The 4th consumer triggers automatic creation of a 4th partition to balance the group" } },
    "kk-095": { optionEdits: { 0: "userA=Faro and userC=Braga; the older userA record is dropped and the tombstone deletes userB", 3: "userA=Lisbon and userB=Porto, because compaction keeps the oldest record it has seen per key" } },
    "kk-096": { optionEdits: { 0: "Only an in-sync-replica-set member, which prevents losing acknowledged records", 2: "No replica may take over — the partition stays offline until the original leader broker returns" } },
    "kk-097": { optionEdits: { 0: "Retries can no longer duplicate or reorder within a partition — each record is written once", 3: "Duplicates are still written on every retry, but consumers are expected to deduplicate them automatically" } },
    "kk-098": { optionEdits: { 0: "At-least-once: a crash between process() and commitSync() reprocesses the batch on restart", 2: "Exactly-once, because commitSync() runs atomically together with the record processing" } },
    "kk-099": { optionEdits: { 0: "The coordinator evicts the consumer and rebalances; raise max.poll.interval.ms or lower max.poll.records", 1: "The broker throttles the consumer's fetches until it speeds up; the fix is to raise fetch.max.bytes substantially" } },
    "kk-100": { optionEdits: { 0: "Deserialization fails (SerializationException) — the bytes aren't a 4-byte integer", 1: "Kafka transparently converts the string to an integer on the broker before delivery to the consumer" } },
    "kk-101": { optionEdits: { 0: "A is asynchronous (send returns a Future, batching in the background); B blocks on get() until ack", 1: "A discards any delivery errors silently, while B is the only way to ever detect a failed send" } },
    "kk-102": { optionEdits: { 0: "Sticky batching: a batch fills to one random partition, then switches, evening out over time", 3: "Strictly one record to each partition in round-robin order, regardless of batching" } },
    "kk-103": { optionEdits: { 0: "Atomic consume-transform-produce: output and offset commit succeed or abort together (read_committed)", 1: "Faster producing overall, because transactions let the producer skip broker acknowledgements" } },
    "kk-104": { optionEdits: { 0: "batch.size and linger.ms tuned together; the trade-off is up to linger.ms of extra latency", 1: "fetch.min.bytes and session.timeout.ms tuned together; the trade-off is much slower group rebalances" } },
    "kk-105": { optionEdits: { 0: "A KStream is a stream of independent events; a KTable upserts, keeping the latest value per key", 3: "A KStream always stores its data on disk, whereas a KTable is held only in memory" } },
    "kk-106": { optionEdits: { 0: "groupBy re-keys to customerId, forcing a repartition before counting; groupByKey avoids it", 1: "count() always forces an internal repartition topic to be created regardless of the current key" } },
    "kk-108": { optionEdits: { 0: "8 — parallelism is bounded by input partitions; the other 4 instances stay idle standbys", 1: "12 — Streams simply splits each partition's records among all of the running instances" } },
    "kk-109": { optionEdits: { 0: "Polls the customers table and publishes rows with a growing id to crm-customers; updates are missed", 1: "Streams every change — inserts, updates, and deletes — from the table using its transaction log" } },
    "kk-110": { optionEdits: { 0: "In internal Kafka topics; throughput scales by raising tasks.max across the worker cluster", 1: "In a shared filesystem visible to every worker; throughput scales only by adding CPU to one worker" } },
    "kk-111": { optionEdits: { 0: "Small per-record edits are what SMTs are for; heavier joins/aggregations belong in a stream processor", 3: "SMTs fully support aggregations and joins, so essentially all processing can move into the connector" } },
    "kk-114": { optionEdits: { 0: "The group is falling behind — ~13k records of lag per partition; watch records-lag-max", 1: "The brokers are dropping records under load; the metric to watch is under-replicated-partitions" } },
    "kk-115": { optionEdits: { 0: "record-error-rate / record-retry-rate rising above zero; add a send callback to log failures", 2: "under-min-isr-partition-count climbing on the broker; the fix is to raise the replication factor" } },
    "kk-093": { optionEdits: { 2: "Use one single consumer with a very large fetch size to read every session in order" } },
    "kk-094": { optionEdits: { 2: "In ZooKeeper znodes, which all modern Kafka versions still rely on for offsets" } },
    "kk-107": { optionEdits: { 2: "cleanup.policy=compact on each of the output topics to remove duplicate keys" } },
    "kk-112": { optionEdits: { 1: "A production-like three-broker cluster running in a dedicated staging environment" } },
    "kk-113": { optionEdits: { 3: "Skip unit tests entirely; only full integration tests can meaningfully cover producer code" } },

    // --- kk-001..090: trim long correct + extend top distractor ---
    "kk-014": { optionEdits: { 1: "Kafka transactions: a transactional.id producer writing output and committing offsets atomically (read_committed)", 0: "Setting enable.idempotence=true on the producer, which is sufficient for exactly-once on its own" } },
    "kk-058": { optionEdits: { 1: "At-least-once: processed-but-uncommitted records replay after a rebalance — use idempotency or EOS", 2: "The producer's compression codec is silently corrupting the batches it sends downstream" } },
    "kk-061": { optionEdits: { 1: "The producer outpaces the cluster: batches fill buffer.memory until send() blocks and times out", 0: "The consumers on the other side of the topic are lagging far behind the producer" } },
    "kk-042": { optionEdits: { 1: "Set value.converter=AvroConverter with a schema.registry.url — converters are separate from connectors", 0: "The JDBC source connector always emits Avro records by default without any converter config" } },
    "kk-077": { optionEdits: { 1: "Table joins enrich each event with the table's current value; stream-stream joins pair events in a window", 3: "Stream-stream joins never require the two input streams to be co-partitioned on the join key" } },
    "kk-088": { optionEdits: { 1: "80 ms/record caps 4 consumers near 50 rec/s vs 100/s in — process faster or add parallelism", 2: "The network path between the clients and the brokers is the true throughput bottleneck here" } },
    "kk-021": { optionEdits: { 0: "The topic is corrupt and must be deleted and recreated from scratch to recover" } },
    "kk-073": { optionEdits: { 3: "Compatibility is guaranteed in both directions, forever, once FORWARD is set on the subject" } },
    "kk-074": { optionEdits: { 0: "The 'latest' schema in the registry is always the wrong one to decode any record with" } },
    "kk-078": { optionEdits: { 0: "Nothing can help here; the 50 GB of RocksDB state is simply lost when the instance dies" } },
    "kk-047": { optionEdits: { 0: "They are the recommended choice for production because of their operational simplicity" } },
    "kk-022": { optionEdits: { 0: "Restart the consumer repeatedly until the poison record somehow gets through" } },
    "kk-038": { optionEdits: { 0: "Write a custom producer and a custom consumer application for each connected system" } },
    "kk-053": { optionEdits: { 0: "Instantiate a fresh KafkaProducer inside every single method that needs to send" } },
    "kk-037": { optionEdits: { 0: "A server process that must be installed and run on each Kafka broker in the cluster" } },
    "kk-019": { optionEdits: { 0: "The new schema must be readable by the old schema, so producers must upgrade first" } },
    "kk-008": { optionEdits: { 0: "security.protocol=PLAINTEXT combined with a topic ACL to secure the connection" } },
    "kk-020": { optionEdits: { 0: "The full Avro schema is embedded inside every single message on the wire" } },
    "kk-041": { optionEdits: { 0: "A connector and a task are simply two names for exactly the same thing" } },
    "kk-050": { optionEdits: { 0: "Call Thread.sleep() in the test until the aggregation window naturally closes" } },
    "kk-011": { optionEdits: { 0: "Nothing changes — Kafka automatically rebalances the existing data across partitions" } },
    "kk-029": { optionEdits: { 0: "A relational database that the user configures and points the state store at" } },
    "kk-051": { optionEdits: { 0: "Branching and split logic within the processing topology itself" } },
    "kk-062": { optionEdits: { 3: "The number of connectors currently deployed across the whole cluster" } },
    "kk-086": { optionEdits: { 3: "Nowhere — the registry already blocks incompatible schemas at produce time anyway" } },
    "kk-081": { optionEdits: { 0: "Set value.converter=StringConverter so the sink reads the records as plain strings" } },
    "kk-033": { optionEdits: { 0: "It fails at startup, because re-keying a stream before a join is not permitted" } },
    "kk-059": { optionEdits: { 0: "Fork and patch the Kafka client library to add the telemetry hooks" } },
    "kk-028": { optionEdits: { 0: "A KTable join, which requires both inputs co-partitioned on the same key" } },
    "kk-064": { optionEdits: { 2: "Producers write to the leader while consumers read only from follower replicas" } },
    "kk-043": { optionEdits: { 0: "A separate custom Kafka Streams job inserted into the pipeline before the sink" } },
    "kk-048": { optionEdits: { 0: "A Testcontainers-based real Kafka broker started for the test" } },
    "kk-012": { optionEdits: { 0: "They determine which partition a record is ultimately written to" } },
    "kk-040": { optionEdits: { 0: "By editing server.properties and restarting the brokers in the cluster" } },
    "kk-060": { optionEdits: { 0: "In the message key, replacing the record's original business key" } },
    "kk-083": { optionEdits: { 0: "Add more partitions to the source topic before anything else" } },
    "kk-085": { optionEdits: { 0: "Run the application against production and wait for a real failure to occur" } },
    "kk-044": { optionEdits: { 0: "Set errors.tolerance=none so the first malformed record stops the task" } },
    "kk-068": { optionEdits: { 0: "None — acks=1 is already fully durable against any kind of broker failure" } },
    "kk-006": { optionEdits: { 0: "Records older than retention.ms are deleted regardless of their key or value" } },
    "kk-007": { optionEdits: { 3: "Both groups must be configured with an identical number of consumers to work" } },
    "kk-065": { optionEdits: { 3: "The group fails to start because consumer count must evenly divide partition count" } },
    "kk-013": { optionEdits: { 0: "Duplicates caused by the application code itself calling send() twice for one record" } },
    "kk-026": { optionEdits: { 2: "The application fails to start when there are more instances than input partitions" } }
  }
};
