/* CCDAK · final flip. Extend the top distractor decisively past the correct
 * answer with a plausible, still-wrong clause so length stops predicting the
 * answer. Leaves a minority correct-longest (target ~30-40%, like MCD1). */
module.exports = {
  questions: {
    "kk-052": { optionEdits: { 0: "Deploy the schema change straight to production and simply monitor the downstream consumer logs for any errors afterward" } },
    "kk-045": { optionEdits: { 2: "It keeps working even while the source database is completely stopped, since it reads from a cached snapshot instead" } },
    "kk-057": { optionEdits: { 0: "The whole cluster is undersized and simply needs more brokers added before any single-partition lag will improve" } },
    "kk-090": { optionEdits: { 3: "In log-segment rotation on the brokers, which quietly stalls the pipeline whenever segments roll over under load" } },
    "kk-021": { optionEdits: { 0: "The topic is corrupt and must be deleted and then recreated from scratch to recover from the recurring leadership errors" } },
    "kk-074": { optionEdits: { 0: "The 'latest' schema in the registry is always the wrong one to decode any record written by an older producer version" } },
    "kk-078": { optionEdits: { 0: "Nothing can really help here; the entire 50 GB of RocksDB state is simply lost for good the moment the instance dies" } },
    "kk-047": { optionEdits: { 0: "They are the recommended choice for production because of their operational simplicity and very low overhead" } },
    "kk-022": { optionEdits: { 0: "Restart the consumer over and over until the poison record somehow gets through and normal processing continues" } },
    "kk-038": { optionEdits: { 0: "Write a fully custom producer and consumer application for each connected system in the integration pipeline" } },
    "kk-053": { optionEdits: { 0: "Instantiate a brand-new KafkaProducer inside every single method that needs to send a record downstream to Kafka" } },
    "kk-037": { optionEdits: { 0: "A dedicated server process that must be installed and kept running on each and every Kafka broker in the cluster" } },
    "kk-019": { optionEdits: { 0: "The new schema must be readable by the old schema, so the producers are the side that must upgrade first" } },
    "kk-008": { optionEdits: { 0: "security.protocol=PLAINTEXT together with a topic ACL to secure the client connection to the SCRAM cluster" } },
    "kk-020": { optionEdits: { 0: "The complete Avro schema is embedded inside every single message that is written to the topic on the wire" } },
    "kk-041": { optionEdits: { 0: "A connector and a task are really just two interchangeable names for exactly the same underlying thing" } },
    "kk-050": { optionEdits: { 0: "Call Thread.sleep() in the test and simply wait until the aggregation window naturally closes on its own" } },
    "kk-011": { optionEdits: { 0: "Nothing changes — Kafka automatically rebalances all of the existing data across the new partitions" } },
    "kk-055": { optionEdits: { 3: "Kafka client metrics must be instrumented and exported manually from within the application code by the developer" } },
    "kk-029": { optionEdits: { 0: "A relational database that the user separately configures and points each state store at for durability" } },
    "kk-051": { optionEdits: { 0: "Branching and split logic within the processing topology itself, which can only run against a live broker" } },
    "kk-062": { optionEdits: { 3: "The number of connectors currently deployed across the whole cluster and their aggregate throughput" } },
    "kk-086": { optionEdits: { 3: "Nowhere — the registry already blocks incompatible schemas at produce time, so CI checks add nothing" } },
    "kk-061": { optionEdits: { 0: "The consumers on the other side of the topic are lagging far behind and back-pressuring the producer" } },
    "kk-081": { optionEdits: { 0: "Set value.converter=StringConverter so that the sink simply reads all of the records as plain strings" } },
    "kk-105": { optionEdits: { 3: "A KStream always persists its data on disk, whereas a KTable is held purely in memory at all times" } },
    "kk-033": { optionEdits: { 0: "It fails at startup, because re-keying a stream immediately before a join is simply not permitted" } },
    "kk-059": { optionEdits: { 0: "Fork and patch the Kafka client library itself to add the telemetry hooks into send and receive paths" } },
    "kk-028": { optionEdits: { 0: "A plain KTable join, which requires both inputs to be co-partitioned on exactly the same join key" } },
    "kk-064": { optionEdits: { 2: "Producers write to the leader while consumers by default read only from the follower replicas instead" } },
    "kk-043": { optionEdits: { 0: "A separate, custom Kafka Streams job inserted into the pipeline just before the sink connector runs" } },
    "kk-093": { optionEdits: { 2: "Use a single consumer instance with a very large fetch size to read every session strictly in order" } },
    "kk-102": { optionEdits: { 3: "Strictly one record to each partition in round-robin order, regardless of any batching behaviour" } },
    "kk-048": { optionEdits: { 0: "A Testcontainers-based real Kafka broker started up specifically for the duration of every test run" } },
    "kk-012": { optionEdits: { 0: "They determine which partition a given record is ultimately written to by the producer's partitioner" } },
    "kk-040": { optionEdits: { 0: "By editing each broker's server.properties file and then restarting all of the brokers in the cluster" } },
    "kk-060": { optionEdits: { 0: "In the message key, overwriting the record's original business key with the propagated trace ID" } },
    "kk-083": { optionEdits: { 0: "Add many more partitions to the source topic first, before attempting any other scaling step at all" } },
    "kk-036": { optionEdits: { 3: "Increase the internal changelog topic's replication factor so that more instances can process in parallel" } },
    "kk-085": { optionEdits: { 0: "Run the whole application against production and simply wait for a real broker failure to occur naturally" } },
    "kk-016": { optionEdits: { 3: "linger.ms is configured far too high on the producer side, delaying every single batch it sends out" } },
    "kk-044": { optionEdits: { 0: "Set errors.tolerance=none so that the very first malformed record immediately stops the whole task" } },
    "kk-017": { optionEdits: { 2: "Whenever the consumer's lag on any partition climbs above a preconfigured threshold value at runtime" } },
    "kk-035": { optionEdits: { 0: "Poll the input far less frequently so that the aggregation emits fewer intermediate window updates" } },
    "kk-054": { optionEdits: { 0: "The total elapsed wall-clock time since the consumer last called poll() against the broker" } },
    "kk-009": { optionEdits: { 2: "The consumer is simply configured with the wrong compression codec for that particular topic" } },
    "kk-034": { optionEdits: { 0: "Wall-clock processing time at the moment the record is handled by the stream thread" } },
    "kk-018": { optionEdits: { 2: "Decrease buffer.memory to force the producer into using smaller, more frequent batches" } },
    "kk-024": { optionEdits: { 0: "Applied per record on the broker after receipt, so its benefit is essentially fixed" } },
    "kk-039": { optionEdits: { 0: "In local files stored on each individual worker node across the Connect cluster" } },
    "kk-010": { optionEdits: { 2: "A relational database is what now stores all of the cluster metadata in modern Kafka" } },
    "kk-089": { optionEdits: { 0: "Broker-side plugins installed on every broker across the whole cluster" } }
  }
};
