/* MCD2 · trim pass — make a DISTRACTOR the longest option. Correct options are
 * trimmed (detail lives in optionNotes/explanations); a few tiny-distractor
 * cases also lengthen a distractor. Meaning/answers unchanged. */
module.exports = {
  questions: {
    "m2-004": { optionEdits: { 1: "It bounds how often one message is reprocessed before failing" } },
    "m2-008": { optionEdits: { 1: "One atomic transaction across multiple resources (JMS + DB)" } },
    "m2-012": { optionEdits: { 1: "It rejects repeat message IDs using an Object Store of seen IDs" } },
    "m2-015": { optionEdits: { 1: "Shared cluster-wide state; scheduling runs on the primary node" } },
    "m2-016": { optionEdits: { 1: "Max concurrent executions of the flow, then back-pressure" } },
    "m2-018": { optionEdits: { 1: "Until Successful with maxRetries=3, millisBetweenRetries=2000" } },
    "m2-023": { optionEdits: { 1: "mule-maven-plugin config + mvn deploy -DmuleDeploy" } },
    "m2-025": { optionEdits: { 1: "Add the Exchange Maven repo and declare the asset's GAV" } },
    "m2-028": { optionEdits: { 1: "Package as a Mule plugin/library, publish to Exchange, depend on it" } },
    "m2-029": { optionEdits: { 1: "The app descriptor (minMuleVersion, secureProperties, etc.)" } },
    "m2-030": { optionEdits: { 1: "Specs, connectors, templates, and policies" } },
    "m2-031": { optionEdits: { 1: "One artifact; per-env YAML selected at deploy time; secrets injected" } },
    "m2-034": { optionEdits: { 1: "In settings.xml or CI secrets, never in source control" } },
    "m2-036": { optionEdits: { 1: "v1 keeps running; v2 releases separately; v1 later deprecated" } },
    "m2-039": { optionEdits: { 1: "In two-way TLS the client also presents a cert the server validates" } },
    "m2-041": { optionEdits: { 1: "Supplied at deployment time (hidden RM property or CI secret)" } },
    "m2-044": { optionEdits: { 1: "Client ID enforcement or OAuth token enforcement" } },
    "m2-046": { optionEdits: { 1: "Its value is masked/hidden in Runtime Manager and logs" } },
    "m2-047": { optionEdits: { 1: "Secure-property encryption plus a requester-side truststore" } },
    "m2-050": { optionEdits: { 1: "A valid OAuth bearer token with required scopes" } },
    "m2-052": { optionEdits: { 1: "More throughput; entries may be lost on a crash" } },
    "m2-054": { optionEdits: { 1: "API Manager alerts (or Anypoint Monitoring)", 3: "In the API's RAML specification document itself" } },
    "m2-056": { optionEdits: { 1: "Publish named business milestones visible in Monitoring" } },
    "m2-057": { optionEdits: { 1: "Anypoint Monitoring, or custom Log4j appenders to ELK/Splunk" } },
    "m2-058": { optionEdits: { 1: "Set the Logger category and level per environment in log4j2.xml" } },
    "m2-059": { optionEdits: { 1: "Scheduled black-box tests of live endpoints" } },
    "m2-061": { optionEdits: { 1: "Behavior, Execution, Validation", 0: "Setup, Run, and Report phases in sequence" } },
    "m2-063": { optionEdits: { 1: "It asserts around a processor without replacing it" } },
    "m2-064": { optionEdits: { 1: "munit-maven-plugin coverage config with failBuild=true", 0: "Rely on manual code review to catch low coverage in PRs" } },
    "m2-065": { optionEdits: { 1: "Assert That with an equalTo matcher on #[payload]", 0: "assert-true with an expression referencing #[payload]" } },
    "m2-067": { optionEdits: { 1: "Configure Mock When to 'Then throw' the desired error typeId" } },
    "m2-068": { optionEdits: { 1: "One API instance per environment via autodiscovery" } },
    "m2-069": { optionEdits: { 1: "Publish to Exchange with docs, mocking, and access requests" } },
    "m2-070": { optionEdits: { 1: "Build once; deploy the same versioned JAR per environment" } },
    "m2-071": { optionEdits: { 1: "In src/test/munit; run at build time; excluded from the JAR" } },
    "m2-072": { optionEdits: { 1: "Deprecate, notify a sunset date, then retire it" } },
    "m2-074": { optionEdits: { 1: "It commits — Continue acks the message and the DB write is lost" } },
    "m2-075": { optionEdits: { 1: "Reconnection retries the connection, Until Successful the work" } },
    "m2-076": { optionEdits: { 1: "VM queues never cross apps; use Anypoint MQ or JMS instead" } },
    "m2-078": { optionEdits: { 1: "A Cache scope over a shared OSv2 store, with a TTL" } },
    "m2-079": { optionEdits: { 1: "Classloader isolation — the driver must go in sharedLibraries" } },
    "m2-084": { optionEdits: { 1: "Add the partner's CA to a requester truststore" } },
    "m2-086": { optionEdits: { 1: "PGP-encrypt with the partner's public key before writing" } },
    "m2-087": { optionEdits: { 1: "JWT verifies locally; OAuth introspects at the provider" } },
    "m2-088": { optionEdits: { 1: "Listener keystore + truststore, with client auth required" } },
    "m2-089": { optionEdits: { 1: "Use async loggers; faster but may lose buffer on crash" } },
    "m2-090": { optionEdits: { 1: "Search by the propagated correlation ID" } },
    "m2-091": { optionEdits: { 1: "1=Runtime Manager, 2=API Manager, 3=Monitoring" } },
    "m2-092": { optionEdits: { 1: "Custom Business Events (or structured log fields)" } },
    "m2-094": { optionEdits: { 0: "The munit-maven-plugin coverage config with failBuild=true" } },
    "m2-097": { optionEdits: { 1: "Publish a new MAJOR version (/v2), deprecate v1, notify holders" } },
    "m2-098": { optionEdits: { 0: "Repeatable in-memory can't exceed maxBufferSize (4 MB) → STREAM_MAXIMUM_SIZE_EXCEEDED" } },
    "m2-105": { optionEdits: { 0: "The driver must also be a sharedLibrary in the mule-maven-plugin so the connector sees it" } },
    "m2-109": { optionEdits: { 2: "Outside the project — CI/CD secrets or settings.xml — injected at build time" } },
    "m2-116": { optionEdits: { 0: "Logging returns immediately; a background thread writes; a crash can lose recent entries" } },
    "m2-121": { optionEdits: { 0: "Set expectedErrorType=\"APP:ORDER_NOT_FOUND\" on the munit:test" } },
    "m2-122": { optionEdits: { 0: "MUnit fails the build below 80% application coverage" } }
  }
};
