/* MCIA · second flip pass. Extend the top distractor decisively past the correct
 * answer (a few over-long correct options trimmed). Leaves a minority
 * correct-longest (target ~30-40%, like MCD1). */
module.exports = {
  questions: {
    "ia-030": { optionEdits: { 1: "A cluster shares state via a distributed grid and elects a primary; a server group is just independent servers", 2: "A server group provides fully automatic failover of all in-flight messages, whereas a cluster does not at all" } },
    "ia-080": { optionEdits: { 1: "Nothing — a cluster shares the object store, so duplicates come from elsewhere (id collisions or expiry)", 3: "The Idempotent Message Validator only ever works correctly when the app is deployed on CloudHub, not clusters" } },
    "ia-120": { optionEdits: { 1: "Move the plaintext credentials out of the .properties files and directly into the flow XML instead of encrypting" } },
    "ia-121": { optionEdits: { 2: "Blue-green deployment, where two complete production environments must always run side by side at once" } },
    "ia-049": { optionEdits: { 0: "CloudHub automatically replicates all deployed applications to a second region for full disaster recovery" } },
    "ia-114": { optionEdits: { 1: "The circuit breaker pattern, which protects the downstream ERP from being overloaded by too many requests" } },
    "ia-116": { optionEdits: { 1: "Increase the acknowledgement timeout so that the poison message is simply redelivered a little less often" } },
    "ia-117": { optionEdits: { 2: "Reduce every single flow's maxConcurrency down to 1 in order to eliminate all thread contention entirely" } },
    "ia-036": { optionEdits: { 0: "Each flow owns a dedicated thread pool that the developer must size manually in the app configuration by hand" } },
    "ia-046": { optionEdits: { 0: "Reconnection = message level; redelivery = connection level; Until Successful = whole-flow retries only, never per message" } },
    "ia-054": { optionEdits: { 0: "Add more Mule workers so that the incoming requests all finish faster and the ERP keeps up" } },
    "ia-064": { optionEdits: { 0: "Internal APIs can skip authentication because all of their callers are already inside the trusted network" } },
    "ia-067": { optionEdits: { 3: "Exporting and importing Anypoint Studio projects between environments manually by hand each time" } },
    "ia-110": { optionEdits: { 2: "Standalone Mule runtimes running with no connection to the Anypoint control plane" } },
    "ia-055": { optionEdits: { 0: "Passing the stream straight through to a single downstream write operation without buffering" } },
    "ia-093": { optionEdits: { 0: "A single shared administrator account used for both the human logins and the CI pipelines alike" } },
    "ia-004": { optionEdits: { 0: "Business data payloads flow through the control plane for policy evaluation and central request logging and audit" } },
    "ia-053": { optionEdits: { 0: "Read the whole 10 GB file fully into memory and greatly increase the JVM heap size to fit it" } },
    "ia-040": { optionEdits: { 3: "Use them to replace integration and performance testing across the whole delivery pipeline entirely" } },
    "ia-062": { optionEdits: { 0: "Move the YAML file to a different folder and add a warning comment above the credential entries" } },
    "ia-031": { optionEdits: { 0: "Schedulers run on every node of the cluster, so you must add distributed locking yourself to prevent duplicates" } },
    "ia-068": { optionEdits: { 0: "Rely on the default CloudHub logs, which are conveniently retained forever by the platform at no cost" } },
    "ia-075": { optionEdits: { 0: "The order service calls each downstream system's REST API in a fixed, hard-coded calling sequence one by one" } },
    "ia-082": { optionEdits: { 2: "File-polling sources simply cannot be used inside a Mule runtime cluster at all in any practical scenario" } },
    "ia-091": { optionEdits: { 2: "A Parallel For Each holding all 8 million entries in memory at the same time during the run" } },
    "ia-103": { optionEdits: { 2: "A Parallel For Each scope with its maxConcurrency tuned to a very high value for maximum speed" } },
    "ia-115": { optionEdits: { 1: "A local single-resource transaction on the JMS connector alone, leaving the database operation entirely uncovered" } },
    "ia-051": { optionEdits: { 0: "Call the three backends one after another sequentially and simply rely on cache hits for speed" } },
    "ia-045": { optionEdits: { 0: "An XA transaction spanning all three of the remote booking APIs together at once atomically" } },
    "ia-119": { optionEdits: { 2: "Basic authentication over plain HTTP inside the VPC, relying on TLS only at the outer network perimeter edge" } },
    "ia-032": { optionEdits: { 0: "Deploy the application in the normal way and simply rely on the shared load balancer for all inbound access" } },
    "ia-070": { optionEdits: { 0: "1=a Runtime Manager alert, 2=Functional Monitoring (BAT), 3=Anypoint Monitoring dashboards and metrics" } },
    "ia-034": { optionEdits: { 2: "Whenever more than one Mule application happens to coexist within the same Anypoint Platform organisation at all" } },
    "ia-087": { optionEdits: { 2: "Publish the MQ confirmation message first, and only afterwards call the downstream payment provider API" } },
    "ia-050": { optionEdits: { 0: "Until Successful configured with effectively infinite automatic retries on the failing poison message" } },
    "ia-035": { optionEdits: { 2: "The JDBC driver must be manually copied into the Mule runtime's own lib folder on each CloudHub worker node" } },
    "ia-038": { optionEdits: { 3: "An integration test that physically unplugs the backend server partway through each test run to force the error" } },
    "ia-118": { optionEdits: { 2: "Convert the reference-data call into a Parallel For Each scope over the individual records instead of caching" } },
    "ia-041": { optionEdits: { 2: "Test on one developer's laptop and simply multiply the measured result by the number of production workers deployed" } },
    "ia-069": { optionEdits: { 0: "Async logging is essentially always worse than plain synchronous logging in every possible production scenario" } },
    "ia-044": { optionEdits: { 0: "Wrap the external REST API call inside a full XA transaction to guarantee durability and atomic rollback" } },
    "ia-059": { optionEdits: { 0: "Nothing extra — CloudHub automatically validates any OAuth token that is presented to the deployed workers by callers" } },
    "ia-060": { optionEdits: { 0: "A developer's personal Anypoint username and password stored in the pipeline" } },
    "ia-097": { optionEdits: { 3: "Only to Anypoint Monitoring, with no other log-forwarding destination available to the application at all" } },
    "ia-033": { optionEdits: { 0: "Configure the CloudHub shared load balancer with the customer's own custom TLS certificate for the vanity domain" } },
    "ia-048": { optionEdits: { 2: "DR is fully achieved automatically simply by running two CloudHub workers within a single region for redundancy" } },
    "ia-084": { optionEdits: { 3: "It silently disables back-pressure for the whole flow, letting the source overrun the entire application under load" } },
    "ia-086": { optionEdits: { 0: "Nothing at all; real event sources never execute during any MUnit test run under any circumstances at all" } },
    "ia-039": { optionEdits: { 3: "An error handler that simply returns a 400 status response for any and all input validation failures in the flow" } },
    "ia-109": { optionEdits: { 1: "The CloudHub Shared Load Balancer combined with a simple CNAME DNS record pointing at the deployed application workers" } },
    "ia-122": { optionEdits: { 2: "Enabling verbose debug-level logging permanently in production so as to capture every response body for later manual review" } },
    "ia-047": { optionEdits: { 0: "It can only ever retry at most three times before it permanently gives up on the failing event and drops it" } },
    "ia-065": { optionEdits: { 0: "Applying semantic versioning to the deployable artifact across all of the target environments consistently" } },
    "ia-052": { optionEdits: { 0: "Vertical scaling only — simply triple the vCore size of the single existing worker instance to add headroom" } },
    "ia-085": { optionEdits: { 0: "1=an integration test; 2=a unit test; 3=an MUnit-based test on production-like sizing overall" } },
    "ia-037": { optionEdits: { 3: "Any port at all works fine, because the CloudHub platform automatically rewrites it for you at deploy time" } },
    "ia-058": { optionEdits: { 2: "Secure configuration properties used to store and protect the platform login secrets securely" } },
    "ia-056": { optionEdits: { 3: "Until Successful wrapped around a For Each scope iterating over all of the millions of records" } },
    "ia-092": { optionEdits: { 0: "Add more Mule workers to the deployment so that it can absorb all of the ERP's incoming load" } },
    "ia-066": { optionEdits: { 2: "Run mvn package with the -Pprod profile to build the application for the production target environment" } },
    "ia-061": { optionEdits: { 2: "Automatic penetration testing of all of the deployed applications running at the network perimeter edge" } },
    "ia-078": { optionEdits: { 0: "DataWeave simply cannot handle very large enterprise-wide canonical data types at all in real practice" } },
    "ia-021": { optionEdits: { 2: "DataWeave cannot transform very large enterprise canonical objects efficiently at runtime under heavy load" } },
    "ia-042": { optionEdits: { 0: "Unit-testing individual DataWeave transformation scripts in complete isolation from the surrounding flow" } },
    "ia-063": { optionEdits: { 2: "Reviewing the Anypoint Monitoring metric dashboards for the production API instance over the time window" } }
  }
};
