/* MCIA length-balance + flip. Trim over-long correct options (detail is in the
 * notes) and extend the top distractor past the correct answer with a plausible,
 * still-wrong clause, so length no longer predicts the answer. Targets the
 * MCD1-range (~30-40% longest-correct). */
module.exports = {
  questions: {
    // long correct -> trim + extend top distractor
    "ia-120": { optionEdits: { 0: "Encrypt values with Secure Properties, keep the key out of the repo, and use hidden platform secrets", 1: "Move the plaintext credentials out of the .properties files and directly into the flow XML instead" } },
    "ia-121": { optionEdits: { 0: "Build once and promote one versioned artifact through each environment, externalizing env config", 2: "Blue-green deployment, where two complete production environments must always run side by side" } },
    "ia-113": { optionEdits: { 0: "MUnit with mocked externals runs every CI build; a smaller integration suite runs before promotion", 1: "Only integration tests against real systems, on the grounds that mocked unit tests prove nothing at all" } },
    "ia-117": { optionEdits: { 0: "Mule 4 self-tunes a centralized (UBER) scheduler — investigate real bottlenecks, not per-pool tuning", 2: "Reduce every single flow's maxConcurrency down to 1 in order to eliminate all thread contention" } },
    "ia-111": { optionEdits: { 0: "Both nodes poll and may process the same file twice; set primaryNodeOnly=\"true\" so only the primary polls", 1: "Neither node polls, because file sources are disabled in clusters; move the flow to a standalone runtime instead" } },
    "ia-114": { optionEdits: { 0: "The reliable-acquisition pattern: after the 202, the order can't be lost even if the ERP fails later", 1: "The circuit breaker pattern, which protects the downstream ERP from being overloaded by requests" } },
    "ia-030": { optionEdits: { 1: "A cluster shares state (VM queues, object stores, locks) via a grid and elects a primary; a server group is independent servers", 2: "A server group provides fully automatic failover of in-flight messages, whereas a cluster does not" } },
    "ia-049": { optionEdits: { 1: "OSv2 and MQ are regional — the DR region needs its own instances, state strategy, deploy, and DNS switch", 0: "CloudHub automatically replicates all deployed applications to a second region for disaster recovery" } },
    "ia-046": { optionEdits: { 1: "Reconnection = connection level; Until Successful = in-flow retries; redelivery = per-message source attempts + DLQ", 0: "Reconnection = message level; redelivery = connection level; Until Successful = whole-flow level retries" } },
    "ia-036": { optionEdits: { 1: "Operations declare processing types and run non-blockingly on shared self-tuning pools, with back-pressure", 0: "Each flow owns a dedicated thread pool that the developer must size manually in the configuration" } },
    "ia-100": { optionEdits: { 0: "Publish-subscribe: publish a price-changed event to a topic; each consumer subscribes independently", 1: "Point-to-point queues wired from the PIM integration individually to each of the three downstream systems" } },
    "ia-104": { optionEdits: { 0: "Idempotent receiver: record each message ID in Object Store and skip IDs already processed", 1: "Switch the queue to fire-and-forget so that each message is delivered at most once to the consumer" } },
    "ia-072": { optionEdits: { 1: "The correlation ID propagates via X-Correlation-ID and is logged, so every app logs the same ID", 0: "Each application independently generates its own random correlation ID for the transaction it handles" } },
    "ia-105": { optionEdits: { 0: "Publish the shared error handling as a common Mule plugin to Exchange and reference it from each app", 1: "Create one giant Mule application containing all twelve integrations so the handler exists in one place" } },
    "ia-068": { optionEdits: { 1: "Disable CloudHub logging (org permission) and add a log4j2 appender to Splunk, or use Monitoring forwarding", 0: "Rely on the default CloudHub logs, which are conveniently retained forever by the platform" } },
    "ia-116": { optionEdits: { 0: "Assign a dead-letter queue with a max-delivery threshold, after which the broker moves it to the DLQ", 1: "Increase the acknowledgement timeout so that the poison message is simply redelivered less often" } },
    "ia-099": { optionEdits: { 1: "Publish accepted orders to a persistent queue (Anypoint MQ FIFO) consumed by an ERP-facing app", 0: "Synchronous request-reply straight from the API to the ERP, using a four-hour HTTP request timeout" } },
    "ia-102": { optionEdits: { 0: "The flow fails with MULE:COMPOSITE_ROUTING, which carries the per-route results and failures", 1: "The scatter-gather quietly returns only the successful inventory result and logs the loyalty failure" } },
    // extend top distractor past correct
    "ia-069": { optionEdits: { 0: "Async logging is essentially always worse than plain synchronous logging in every scenario" } },
    "ia-041": { optionEdits: { 2: "Test on a single developer laptop and simply multiply the result by the number of workers" } },
    "ia-052": { optionEdits: { 0: "Vertical scaling only — triple the vCore size of the one existing worker instance" } },
    "ia-122": { optionEdits: { 2: "Enabling debug-level logging permanently in production to capture every response body" } },
    "ia-084": { optionEdits: { 3: "It silently disables back-pressure for the flow, letting the source overrun the app" } },
    "ia-109": { optionEdits: { 1: "The CloudHub Shared Load Balancer combined with a CNAME record pointing at the app" } },
    "ia-059": { optionEdits: { 0: "Nothing — CloudHub automatically validates any OAuth token presented to the workers" } },
    "ia-033": { optionEdits: { 0: "Configure the shared load balancer with the customer's own custom TLS certificate" } },
    "ia-048": { optionEdits: { 2: "DR is achieved automatically simply by running two CloudHub workers in one region" } },
    "ia-115": { optionEdits: { 1: "A local (single-resource) transaction configured on the JMS connector only, not the database" } },
    "ia-004": { optionEdits: { 0: "Business data payloads flow through the control plane for policy evaluation and central logging" } },
    "ia-034": { optionEdits: { 2: "Whenever more than one Mule application happens to exist within the same organisation" } },
    "ia-031": { optionEdits: { 0: "Schedulers run on every node of the cluster, so you must add distributed locking yourself" } },
    "ia-047": { optionEdits: { 0: "It can retry at most three times before permanently giving up on the event" } },
    "ia-075": { optionEdits: { 0: "The order service calls each downstream system's REST API in a fixed, hard-coded sequence" } },
    "ia-119": { optionEdits: { 2: "Basic authentication over plain HTTP inside the VPC, with TLS only on the outside edge" } },
    "ia-038": { optionEdits: { 3: "An integration test that physically unplugs the backend server during the run" } },
    "ia-039": { optionEdits: { 3: "An error handler that returns a 400 status for input validation failures" } },
    "ia-065": { optionEdits: { 0: "Semantic versioning of the deployable artifact across the environments" } },
    "ia-087": { optionEdits: { 2: "Publish the MQ confirmation first, and only then call the payment API afterwards" } },
    "ia-097": { optionEdits: { 3: "Only to Anypoint Monitoring, with no alternative log destination available" } },
    "ia-035": { optionEdits: { 2: "The JDBC driver must be copied into the Mule runtime's lib folder on CloudHub" } },
    "ia-032": { optionEdits: { 0: "Deploy the application normally and rely on the shared load balancer for access" } },
    "ia-044": { optionEdits: { 0: "Wrap the external REST API call inside an XA transaction for durability" } },
    "ia-050": { optionEdits: { 0: "Until Successful configured with effectively infinite retries on the message" } },
    "ia-118": { optionEdits: { 2: "Convert the reference-data call into a Parallel For Each over the records" } },
    "ia-070": { optionEdits: { 0: "1=Runtime Manager alert, 2=Functional Monitoring (BAT), 3=Anypoint Monitoring" } },
    "ia-086": { optionEdits: { 0: "Nothing at all; event sources never execute during any MUnit test run" } },
    "ia-040": { optionEdits: { 3: "Use them to replace integration and performance testing across the pipeline entirely" } },
    "ia-064": { optionEdits: { 0: "Internal APIs can skip authentication because all of their callers are already internal" } },
    "ia-082": { optionEdits: { 2: "File-polling sources simply cannot be used inside a Mule runtime cluster at all" } },
    "ia-008": { optionEdits: { 0: "Queues deliver each message to every consumer, while topics deliver to exactly one subscriber" } },
    "ia-093": { optionEdits: { 0: "A single shared administrator account used for both human logins and the pipelines" } },
    "ia-012": { optionEdits: { 2: "Store the orders in an Object Store that all three downstream systems poll periodically" } },
    "ia-020": { optionEdits: { 2: "Every system must migrate its internal schema to match the shared canonical model" } },
    "ia-053": { optionEdits: { 0: "Read the whole 10 GB file into memory and greatly increase the JVM heap size" } },
    "ia-054": { optionEdits: { 0: "Add more Mule workers so that the incoming requests all finish faster overall" } },
    "ia-067": { optionEdits: { 3: "Exporting and importing Anypoint Studio projects between environments by hand" } },
    "ia-103": { optionEdits: { 2: "A Parallel For Each scope with its maxConcurrency tuned to a high value" } },
    "ia-055": { optionEdits: { 0: "Passing the stream straight through to a single downstream write operation" } },
    "ia-045": { optionEdits: { 0: "An XA transaction spanning all three of the booking APIs at once" } },
    "ia-051": { optionEdits: { 0: "Call the three backends sequentially and simply rely on cache hits" } },
    "ia-091": { optionEdits: { 2: "A Parallel For Each holding all 8 million entries in memory at once" } },
    "ia-071": { optionEdits: { 0: "In the flow XML, where every single deployment increments the major version" } },
    "ia-022": { optionEdits: { 0: "Write DataWeave checks with fail() at the very start of every single flow" } },
    "ia-062": { optionEdits: { 0: "Move the YAML file to a different folder and add a warning comment above it" } },
    "ia-014": { optionEdits: { 1: "When the target system suffers frequent multi-hour outages that must be absorbed" } },
    "ia-026": { optionEdits: { 0: "A server group where each node simply keeps its own in-memory Object Store" } },
    "ia-098": { optionEdits: { 1: "Deploy all of the Mule applications only to CloudHub workers in the eu-central-1 region" } }
  }
};
