/* MCPA de-bias · section p5 (single-answer, governance/policies). */
module.exports = {
  questions: {
    "pa-029": {
      optionEdits: {
        0: "One API instance shared across dev, test, and prod",
        2: "Policies declared inside the API's RAML specification",
        3: "An instance only in prod; lower environments run unmanaged"
      },
      optionNotes: [
        "A shared instance can't hold per-environment api.id, policies, or contracts.",
        "Correct — one instance per environment, each with its own api.id, policies, SLA tiers, contracts, and alerts.",
        "Policies are configured on the API instance in API Manager, not in the RAML.",
        "Lower environments also need managed instances to test policy behavior before prod."
      ]
    },
    "pa-030": {
      optionEdits: {
        0: "Rate limiting, which hard-rejects requests over the limit",
        2: "Client ID enforcement to identify each caller",
        3: "A CORS policy to control browser origins"
      },
      optionNotes: [
        "Rate limiting rejects the surplus outright, so it can't absorb bursts.",
        "Correct — spike control smooths bursts by briefly queuing/delaying within limits instead of hard-rejecting.",
        "Client ID enforcement is about identity, not shaping throughput.",
        "CORS governs cross-origin browser calls, unrelated to backend rate protection."
      ]
    },
    "pa-031": {
      optionEdits: {
        0: "A wiki page documenting the required standards for teams to follow",
        1: "Automated policies applied at the organization/environment level to every API instance",
        2: "Manually applying the policies to each API on every release",
        3: "A custom connector each team adds to its implementation"
      },
      optionNotes: [
        "Documentation relies on people remembering — exactly what the requirement rules out.",
        "Correct — automated (org/environment-level) policies apply to all instances, present and future, without per-team effort.",
        "Manual per-release application is error-prone and doesn't cover future instances automatically.",
        "A connector is implementation code, not enforced governance across all instances."
      ]
    },
    "pa-032": {
      optionEdits: {
        0: "1=proxy, 2=embedded gateway, 3=proxy",
        1: "1=embedded gateway via autodiscovery, 2=API proxy generated by API Manager, 3=Flex Gateway",
        2: "All three enforced through Flex Gateway",
        3: "1=Flex Gateway, 2=embedded gateway, 3=API proxy"
      },
      optionNotes: [
        "A CloudHub Mule app can enforce embedded via autodiscovery; a proxy adds a needless hop.",
        "Correct — Mule app -> embedded autodiscovery; unmodifiable .NET -> API-Manager proxy; K8s edge -> Flex Gateway.",
        "Flex Gateway fits the edge case but not the Mule app, which enforces embedded.",
        "The .NET service can't run embedded policies, and the Mule app shouldn't need Flex."
      ]
    },
    "pa-033": {
      optionEdits: {
        0: "Query parameters are parsed more slowly than headers",
        1: "Credentials end up in URLs — cached, logged by proxies and access logs, visible in browser history; headers (or Basic auth) keep them out of URLs",
        2: "APIs are unable to read values from query parameters",
        3: "Query parameters interfere with rate-limiting counters"
      },
      optionNotes: [
        "Performance isn't the concern; exposure of secrets in URLs is.",
        "Correct — secrets in URLs get cached, logged, and stored in history; headers keep them out of the URL.",
        "APIs can read query params fine; the problem is leakage, not capability.",
        "Rate limiting keys off identity/contract, not param placement."
      ]
    },
    "pa-034": {
      optionEdits: {
        0: "401 Unauthorized, since the tier no longer applies",
        1: "429 Too Many Requests once the tier limit is exceeded",
        2: "500 Internal Server Error from the overloaded backend",
        3: "403 Forbidden on every request for the rest of the minute"
      },
      optionNotes: [
        "Credentials are valid, so it isn't a 401 authentication failure.",
        "Correct — traffic beyond the SLA-tier limit is throttled with HTTP 429.",
        "The gateway rejects the surplus before the backend, so it isn't a 500.",
        "403 is authorization denial; exceeding a rate limit returns 429, and only the excess is rejected."
      ]
    },
    "pa-035": {
      optionEdits: {
        0: "Email the API team and wait for credentials to be issued",
        1: "Find the API in Exchange -> request access with a client application -> select an SLA tier -> contract approved (auto or manual) -> use the issued client_id/secret per the API's documented mechanism",
        2: "Deploy a personal proxy in front of the API",
        3: "Clone the API's implementation repository and run it locally"
      },
      optionNotes: [
        "Manual email issuance bypasses the governed self-service contract flow.",
        "Correct — discover in Exchange, request access with an app, pick a tier, get the contract approved, then use the credentials.",
        "Consumers don't front the API with their own proxy to gain access.",
        "Access is granted via a contract, not by cloning and self-hosting the implementation."
      ]
    },
    "pa-037": {
      optionEdits: {
        0: "Only at the Experience API; the inner APIs trust the outer layer",
        1: "At EVERY layer — each API instance enforces its own authentication/limits (zero trust inside the network)",
        2: "Only at the System APIs closest to the data",
        3: "Policies are optional for internal-only APIs"
      },
      optionNotes: [
        "Trusting the outer layer leaves inner APIs exposed if that layer is bypassed.",
        "Correct — enforce at every layer; each instance authenticates and limits its own callers (zero trust).",
        "Guarding only System APIs leaves Process/Experience layers unprotected.",
        "Internal APIs still need enforcement; 'internal' is not a security boundary."
      ]
    },
    "pa-038": {
      optionEdits: {
        0: "The policy executes twice per request",
        1: "The policy applies only to matching methods/paths (e.g., POST /orders), leaving other operations unaffected",
        2: "It disables the policy for the whole instance",
        3: "Resource-level scoping is available only for custom policies"
      },
      optionNotes: [
        "Scoping to a resource doesn't duplicate execution.",
        "Correct — a resource-level policy runs only for the matched methods/paths, not the whole API.",
        "Scoping narrows where the policy runs; it doesn't turn it off.",
        "Resource-level application works for included policies too, not just custom ones."
      ]
    },
    "pa-039": {
      optionEdits: {
        0: "Basic authentication against a user directory",
        1: "JWT validation — signatures verified locally against the provider's JWKS; expiry and claims checked without per-request round trips",
        2: "OAuth token introspection called on every request",
        3: "IP allowlisting of known consumer networks"
      },
      optionNotes: [
        "Basic auth isn't OAuth and sends credentials on every call.",
        "Correct — JWT validation checks signatures/claims locally via JWKS, avoiding a per-request auth-server hop.",
        "Introspection on every call adds exactly the latency and load the requirement forbids.",
        "IP allowlisting is network-level and doesn't provide OAuth consumer identity."
      ]
    },
    "pa-040": {
      optionEdits: {
        0: "Worker CPU and memory metrics from the runtime",
        1: "API Manager analytics — invocations are attributed to client applications via their credentials/contracts",
        2: "The application's own log files, grepped per consumer",
        3: "Exchange asset download counts for the API"
      },
      optionNotes: [
        "CPU metrics describe infrastructure health, not per-consumer usage.",
        "Correct — API Manager analytics attribute calls to client apps through their credentials/contracts.",
        "Logs can show requests but aren't the governed per-consumer usage report.",
        "Download counts measure discovery interest, not runtime API consumption."
      ]
    }
  }
};
